grokonez:
    app:
        jwtExpiration: 86400
        jwtSecret: jwtErotemeSecretKey
server:
    port: 8084
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/register?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
        username: root
        password: root
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create
            show-sql: true
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    rabbitmq:
        host: localhost
        port: 5672

